apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: buildah-dk-pipeline
spec:
  resources:
    - name: docker-source
      type: git
    - name: builtImage
      type: image
  tasks:
    - name: build-task
      resources:
        inputs:
          - name: docker-source
            resource: dakwebstormtest-image
        outputs:
          - name: builtImage
            resource: skaffold-git
      taskRef:
        name: buildah-dk