apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  name: demo-pipeline-run-2
spec:
  pipelineRef:
    name: buildah-dk-pipeline
  serviceAccountName: 'tekton-pipelines-controller'
  resources:
    - name: skaffold-git
      resourceRef:
        name: skaffold-git
    - name: dakwebstormtest-image
      resourceRef:
        name: dakwebstormtest-image