apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  name: source-to-image-2
spec:
  serviceAccountName: tutorial-service
  taskRef:
    name: source-to-image-2
  inputs:
    resources:
      - name: docker-source
        resourceRef:
          name: skaffold-git
    params:
      - name: pathToDockerFile
        value: Dockerfile
      - name: pathToContext
        value: .
  outputs:
    resources:
      - name: builtImage
        resourceRef:
          name: dakwebstormtest-image