apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: source-to-image-2
spec:
  inputs:
    resources:
      - name: docker-source
        type: git
    params:
      - name: pathToContext
        description: The path to the build context used by Kaniko  within the workspace
        default: .
      - name: pathToDockerFile
        description: The path to the dockerfile to build (relative to the context)
        default: Dockerfile
  outputs:
   resources:
      - name: builtImage
        type: image
  steps:
    - name: build-and-push
      image: gcr.io/kaniko-project/executor

      command:
        - /kaniko/executor
      args:
        - --dockerfile=${inputs.params.pathToDockerFile}
        - --destination=$(outputs.resources.builtImage.url)
        - --context=/workspace/docker-source/${inputs.params.pathToContext}
